### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by GHRAIRIAnouer99** [ravi-more/reactjs-ros-robot-control-console-web#3]
ravi-plus pourqoui elle me donne toujoursoffline? quel paramétre que je devais modifier 
pour visualiser mon robot à cette page web
?

**Comment by ravi-more** [comment]
Essentiellement, le but de la configuration du serveur Ros Bridge est d'établir la communication entre l'application frontale et le robot. Le serveur Ros Bridge joue le rôle d'intermédiaire, permettant à l'application front-end de publier et de s'abonner à des sujets. Cela permet à l'application frontale, développée avec React, d'interagir avec le robot en envoyant et en recevant des informations via des sujets. En configurant le serveur Ros Bridge, l'application frontale se connecte au robot, permettant une communication transparente entre les deux.

Pour configurer le serveur Ros Bridge, ajoutez la configuration suivante à
`src/data/config.js`

```JavaScript

const Config = {
    ROSBRIDGE_SERVER_IP: "127.0.0.1",
    ROSBRIDGE_SERVER_PORT: "9090",
    CMD_VEL_TOPIC: "/cmd_vel",
    GOAL_TOPIC: "/move_base_simple/goal",
    VIDEO_STREAM_URL: "http://0.0.0.0:8080/stream?topic=/camera/rgb/image_raw&type=mjpeg&width=300&height=200"
};
```

J'espère que cela résoudra votre problème
